baseURL = 'https://guide.data.gouv.nc/'
languageCode = 'fr'
defaultContentLanguage = 'fr'
title = 'data.gouv.nc'
theme = 'book'

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
disqusShortname = ""

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = 'Logo_GUIDEDATAGOUVNC.png'
  BookSection = '*'
  BookRepo = 'https://github.com/gouv-nc-data/guide-datagouvnc'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
  BookDateFormat = '2 Jan 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true
  BookFavicon = "favicon.png"
  

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 0
    title = ""
    languageCode = "fr"
    contentDir = "content/fr"

